FROM ubuntu:focal

# setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# basic stuff
RUN apt update
RUN apt install -q -y --no-install-recommends build-essential tmux vim git sudo ssh

COPY misc/bashrc_ubuntu_20_04_sandbox /root/.bashrc

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone
RUN ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN apt install -q -y --no-install-recommends tzdata

# copy ssh keys from system into container
ARG ssh_prv_key
ARG ssh_pub_key

RUN mkdir -p /root/.ssh/
RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
    echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
    chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub
