FROM ubuntu:focal

# setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

# basic stuff
RUN apt update
RUN apt install -q -y --no-install-recommends build-essential tmux vim git python3 python3-pip

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone
RUN ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN apt install -q -y --no-install-recommends tzdata

# setup ROS
RUN apt install -q -y --no-install-recommends dirmngr gnupg2 curl ca-certificates
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'

# barebones ros installation
# - we want all packages to be installed as dependencies of our packages
RUN apt update
RUN apt install -q -y --no-install-recommends ros-noetic-desktop
RUN apt install -q -y --no-install-recommends python3-rosdep
RUN rosdep init

# install catkin
RUN apt install -q -y --no-install-recommends python3-catkin-tools
RUN apt install -q -y --no-install-recommends python3-catkin-lint

# install misc stuff
RUN apt install -q -y --no-install-recommends ranger neofetch
RUN apt install -q -y --no-install-recommends qt5-style-kvantum qt5-style-kvantum-themes
RUN apt install -q -y --no-install-recommends zsh

RUN echo "root:docker" | chpasswd
RUN useradd -g sudo -ms /usr/bin/zsh docker
RUN echo "docker:docker" | chpasswd

USER docker
WORKDIR /home/docker

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-/home/docker/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-/home/docker/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
COPY misc/zshrc_ros_noetic_workspace /home/docker/.zshrc

RUN git clone https://github.com/tmux-plugins/tpm /home/docker/.tmux/plugins/tpm

# copy ssh keys from system into container
ARG ssh_prv_key
ARG ssh_pub_key

RUN mkdir -p /home/docker/.ssh/
RUN echo "$ssh_prv_key" > /home/docker/.ssh/id_rsa && \
    echo "$ssh_pub_key" > /home/docker/.ssh/id_rsa.pub && \
    chmod 600 /home/docker/.ssh/id_rsa && \
    chmod 600 /home/docker/.ssh/id_rsa.pub

# make docker source the ros installation
COPY misc/entrypoint_ros_noetic_workspace.sh /home/docker/entrypoint.sh

ENTRYPOINT ["/home/docker/entrypoint.sh"]
CMD ["tmux"]
